/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guest.view;

import car.controller.CarController;
import carowner.controller.CarOwnerController;
import cartravel.controller.CarTravelController;
import cartravel.dao.MysqlCarTravelDao;
import cartravel.model.CarTravel;
import guest.model.Guest;
import information.controller.InformationController;
import information.model.Information;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import login.view.LoginForm;
import utils.SendMail;

/**
 *
 * @author kienanh2903
 */
public class HomeGuest extends javax.swing.JFrame {

    CarOwnerController coc;
    CarController cc;
    CarTravelController ctc;
    InformationController ic;
    List<Information> listInformations;
    private int stt = 1;

    /**
     * Creates new form HomeGuess
     */
    public HomeGuest() {
        initComponents();
        setVisiableNews();
        coc = new CarOwnerController();
        cc = new CarController();
        ctc = new CarTravelController();
        coc.displayInforCarOwnerToJTable(jTable1);
        ic = new InformationController();
        listInformations = ic.getAllInfor();
        setVisiablePrevious();
        setVisiableNext();
        ic.displayInformation(jPanel4, jPanel_news, listInformations, stt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_bookticket = new javax.swing.JPopupMenu();
        jMenuItem_bookticket = new javax.swing.JMenuItem();
        jDialog_bookTicket = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_bsx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nhaXe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_giaVe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_soGhe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_lichTrinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_loTrinh = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jXDatePicker1_ngayDatVeDi = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jTextField_cmt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ten = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jXDatePicker_ngaySinh = new org.jdesktop.swingx.JXDatePicker();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jRadioButton_nu = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_sdt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_diaChi = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel_news = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_next = new javax.swing.JLabel();
        jLabel_before = new javax.swing.JLabel();
        jPanel_bookticket = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_searchCarForBookTicket = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_unbookticket = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField_maChuyenXe = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField_cmtKhach = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel_searchInfor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem_bookticket.setText("Đặt vé");
        jMenuItem_bookticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_bookticketActionPerformed(evt);
            }
        });
        jPopupMenu_bookticket.add(jMenuItem_bookticket);

        jDialog_bookTicket.setTitle("Trang đặt vé dành cho khách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đặt vé online");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin xe"));

        jLabel4.setText("Biển số xe : ");

        jTextField_bsx.setEditable(false);

        jLabel5.setText("Nhà xe :");

        jTextField_nhaXe.setEditable(false);

        jLabel7.setText("Giá vé :");

        jTextField_giaVe.setEditable(false);

        jLabel8.setText("Số ghế :");

        jTextField_soGhe.setEditable(false);

        jLabel9.setText("Lịch trình :");

        jTextField_lichTrinh.setEditable(false);

        jLabel10.setText("Lộ trình :");

        jTextField_loTrinh.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_bsx, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_soGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_loTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_nhaXe, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jTextField_giaVe)
                    .addComponent(jTextField_lichTrinh))
                .addGap(34, 34, 34))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_bsx, jTextField_giaVe, jTextField_lichTrinh, jTextField_loTrinh, jTextField_nhaXe, jTextField_soGhe});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_bsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nhaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_giaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_lichTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_soGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_loTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_bsx, jTextField_giaVe, jTextField_lichTrinh, jTextField_loTrinh, jTextField_nhaXe, jTextField_soGhe});

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel11.setText("Ngày đặt vé đi : ");

        jXDatePicker1_ngayDatVeDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1_ngayDatVeDiActionPerformed(evt);
            }
        });

        jLabel12.setText("Chứng minh thư :");

        jLabel6.setText("Họ tên : ");

        jLabel14.setText("Ngày sinh :");

        jXDatePicker_ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker_ngaySinhActionPerformed(evt);
            }
        });

        jLabel15.setText("Giới tính :");

        buttonGroup1.add(jRadioButton_nam);
        jRadioButton_nam.setSelected(true);
        jRadioButton_nam.setText("Nam");

        buttonGroup1.add(jRadioButton_nu);
        jRadioButton_nu.setText("Nữ");

        jLabel16.setText("Số điện thoại :");

        jLabel17.setText("Email :");

        jLabel19.setText("Địa chỉ :");

        jButton3.setText("Đặt vé");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jXDatePicker1_ngayDatVeDi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_diaChi)
                            .addComponent(jXDatePicker_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTextField_cmt)
                            .addComponent(jTextField_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jRadioButton_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_email))))
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXDatePicker1_ngayDatVeDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_nam)
                    .addComponent(jRadioButton_nu))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jDialog_bookTicketLayout = new javax.swing.GroupLayout(jDialog_bookTicket.getContentPane());
        jDialog_bookTicket.getContentPane().setLayout(jDialog_bookTicketLayout);
        jDialog_bookTicketLayout.setHorizontalGroup(
            jDialog_bookTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_bookTicketLayout.setVerticalGroup(
            jDialog_bookTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_bookTicketLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("jLabel13");

        jLabel18.setText("Email :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new java.awt.GridLayout(2, 3));

        jLabel2.setText("Đầu ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel_next.setText("Tiếp >>");
        jLabel_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseClicked(evt);
            }
        });

        jLabel_before.setText("<< Trước");
        jLabel_before.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_beforeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_newsLayout = new javax.swing.GroupLayout(jPanel_news);
        jPanel_news.setLayout(jPanel_newsLayout);
        jPanel_newsLayout.setHorizontalGroup(
            jPanel_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_newsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_before)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_next)
                .addContainerGap(598, Short.MAX_VALUE))
            .addGroup(jPanel_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_newsLayout.setVerticalGroup(
            jPanel_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_newsLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addGroup(jPanel_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_next)
                    .addComponent(jLabel_before))
                .addContainerGap())
            .addGroup(jPanel_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_newsLayout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 39, Short.MAX_VALUE)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin cần tìm kiếm :");

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_searchCarForBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_searchCarForBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chuyến xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Biển số xe", "Nhà xe", "Số ghế", "Lộ trình", "Lịch trình", "Giá vé"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu_bookticket);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_bookticketLayout = new javax.swing.GroupLayout(jPanel_bookticket);
        jPanel_bookticket.setLayout(jPanel_bookticketLayout);
        jPanel_bookticketLayout.setHorizontalGroup(
            jPanel_bookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_bookticketLayout.setVerticalGroup(
            jPanel_bookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bookticketLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Hủy đặt vé online");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Bạn vui lòng điền các thông tin cần thiết để xác nhận hủy đăng ký vé xe online");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Mã chuyến xe : ");

        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("*Mã chuyến xe đã được gửi vào email của bạn khi đăng ký.Vui lòng kiểm tra lại.");

        jLabel24.setText("Chứng minh thư của bạn khi đăng ký xe :");

        jButton4.setText("Hủy vé");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_unbookticketLayout = new javax.swing.GroupLayout(jPanel_unbookticket);
        jPanel_unbookticket.setLayout(jPanel_unbookticketLayout);
        jPanel_unbookticketLayout.setHorizontalGroup(
            jPanel_unbookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_unbookticketLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_maChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(jPanel_unbookticketLayout.createSequentialGroup()
                .addGroup(jPanel_unbookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_unbookticketLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_cmtKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_unbookticketLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_unbookticketLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel22, jLabel24});

        jPanel_unbookticketLayout.setVerticalGroup(
            jPanel_unbookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_unbookticketLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel_unbookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_maChuyenXe)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel_unbookticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextField_cmtKhach))
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel_unbookticketLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel22, jLabel24});

        javax.swing.GroupLayout jPanel_searchInforLayout = new javax.swing.GroupLayout(jPanel_searchInfor);
        jPanel_searchInfor.setLayout(jPanel_searchInforLayout);
        jPanel_searchInforLayout.setHorizontalGroup(
            jPanel_searchInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel_searchInforLayout.setVerticalGroup(
            jPanel_searchInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jPanel_news, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel_bookticket, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel_unbookticket, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel_searchInfor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_bookticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_unbookticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_searchInfor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_news, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_bookticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_unbookticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_searchInfor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_news, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/applications_system.png"))); // NOI18N
        jMenu1.setText("Hệ thống");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Đăng nhập");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Thoát");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/utilitie.png"))); // NOI18N
        jMenu2.setText("Tính năng");

        jMenuItem4.setText("Tin tức bến xe");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem1.setText("Đặt vé");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Hủy vé");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Tra cứu thông tin");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        setVisiableNews();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisiableBookTicket();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setVisiableUnBookTicket();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisiableSearchInfor();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String keySearch = jTextField_searchCarForBookTicket.getText();
        cc.displaySearchCarForBookTicket(jTable1, keySearch);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem_bookticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_bookticketActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn xe để đặt vé.Vui lòng chọn lại");
        } else {
            jDialog_bookTicket.setVisible(true);
            jDialog_bookTicket.setSize(620, 600);
            jDialog_bookTicket.setLocationRelativeTo(null);
            Date dateNow = new Date();
            Date ngaySinh = new Date(97, 2, 29);
            jXDatePicker1_ngayDatVeDi.setDate(dateNow);
            jXDatePicker_ngaySinh.setDate(ngaySinh);
            jTextField_bsx.setText(jTable1.getValueAt(index, 0).toString());
            jTextField_nhaXe.setText(jTable1.getValueAt(index, 1).toString());
            jTextField_soGhe.setText(jTable1.getValueAt(index, 2).toString());
            jTextField_giaVe.setText(jTable1.getValueAt(index, 5).toString());
            jTextField_loTrinh.setText(jTable1.getValueAt(index, 3).toString());
            jTextField_lichTrinh.setText(jTable1.getValueAt(index, 4).toString());
        }
    }//GEN-LAST:event_jMenuItem_bookticketActionPerformed

    private void jXDatePicker1_ngayDatVeDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1_ngayDatVeDiActionPerformed
        // TODO add your handling code here:
        Date dateBookTicket = jXDatePicker1_ngayDatVeDi.getDate();
        Date dateNow = new Date();
        Date dateAfter = new Date(dateNow.getTime() + 7 * 24 * 3600 * 1000);
        if (dateBookTicket.before(dateNow)) {
            JOptionPane.showMessageDialog(jDialog_bookTicket, "Bạn không thể đặt vé những ngày đã qua.Vui lòng chọn lại ngày khác!!!");
        } else if (dateBookTicket.after(dateAfter)) {
            JOptionPane.showMessageDialog(jDialog_bookTicket, "Bạn chỉ được đặt vé trong vòng 7 ngày trở lại.Vui lòng chọn lại!!!");
        }
    }//GEN-LAST:event_jXDatePicker1_ngayDatVeDiActionPerformed

    private void jXDatePicker_ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker_ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker_ngaySinhActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng ký chuyến xe này không ??", "Thông báo ",
                JOptionPane.YES_OPTION) == JOptionPane.YES_NO_OPTION) {
            String bienSoXe = jTextField_bsx.getText();
            Date ngayDi = new java.sql.Date(jXDatePicker1_ngayDatVeDi.getDate().getTime());
            String thoiGian = jTextField_lichTrinh.getText();
            String maChuyenXe = ctc.generateCarTravelId(bienSoXe, (java.sql.Date) ngayDi, thoiGian);
            System.out.println(maChuyenXe);
            CarTravel carTravel = new CarTravel(maChuyenXe, bienSoXe, (java.sql.Date) ngayDi, thoiGian);
            String cmt = jTextField_cmt.getText().trim();
            String ten = jTextField_ten.getText().trim();
            Date ngaySinh = new java.sql.Date(jXDatePicker_ngaySinh.getDate().getTime());
            String gioiTinh = "";
            if (jRadioButton_nam.isSelected()) {
                gioiTinh = "Nam";
            } else {
                gioiTinh = "Nữ";
            }
            String sdt = jTextField_sdt.getText().trim();
            String email = jTextField_email.getText().trim();
            String diaChi = jTextField_diaChi.getText().trim();
            Guest guest = new Guest(cmt, ten, (java.sql.Date) ngaySinh, gioiTinh, sdt, email, diaChi);
            int result = ctc.bookTicket(carTravel, guest);
            switch (result) {
                case MysqlCarTravelDao.RESULT_DATE_NULL:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Vui lòng chọn ngày cần đặt vé");
                    break;
                case MysqlCarTravelDao.RESULT_DATE_BORN_NULL:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Bạn phải điền ngày sinh của bạn.Vui lòng điền đầy đủ");
                    break;
                case MysqlCarTravelDao.RESULT_EMPTY:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Bạn phải điền đủ các thông tin");
                    break;
                case MysqlCarTravelDao.RESULT_ERROR_CMT:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Định dạng chứng minh thư không đúng.Vui lòng nhập lại");
                    break;
                case MysqlCarTravelDao.RESULT_ERROR_SDT:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Định dạng số điện thoại không đúng.Vui lòng nhập lại");
                    break;
                case MysqlCarTravelDao.RESULT_ERROR_EMAIL:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Định dạng email không đúng.Vui lòng nhập lại");
                    break;
                case MysqlCarTravelDao.RESULT_GUEST_REGISTED:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Bạn đã đăng ký chuyến xe này rồi.Không thể đăng ký thêm");
                    break;
                case MysqlCarTravelDao.RESULT_SUCCESS:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Đăng ký thành công.Chúng tôi đã gửi các thông tin đến email của bạn.Vui lòng kiểm tra lại");
                    SendMail.send(email, "Đăng ký vé xe online bến xe khách Hà Nội", "Bạn vừa đăng ký vé xe thông qua hệ thống đặt vé online.\n"
                            + "Thông tin chuyến xe:\n"
                            + "Mã chuyến xe : " + maChuyenXe
                            + "Biển số xe : " + bienSoXe + "\n"
                            + "Nhà xe : " + jTextField_nhaXe.getText() + "\n"
                            + "Lộ trình : " + jTextField_loTrinh.getText() + "\n"
                            + "Lịch trình : " + jTextField_lichTrinh.getText() + "\n"
                            + "Giá vé : " + jTextField_giaVe.getText() + "\n"
                            + "Số chứng minh thư bạn đăng ký vé : " + cmt + "\n"
                            + "Vui lòng đến bến xe xác nhận mua vé trước thời hạn hủy vé của bến. Vui lòng cảm ơn quý khách đã sử dụng dịch vụ");
                    break;
                case MysqlCarTravelDao.RESULT_EXCEPTION:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Đã có lỗi xảy ra.Vui lòng thử lại sau");
                    break;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn hủy đăng ký chuyến xe này không ??", "Cảnh báo",
                JOptionPane.YES_OPTION) == JOptionPane.YES_NO_OPTION) {
            String maChuyenXe = jTextField_maChuyenXe.getText().trim();
            String cmt = jTextField_cmtKhach.getText().trim();
            int result = ctc.unbookTicket(maChuyenXe, cmt);
            switch (result) {
                case MysqlCarTravelDao.RESULT_EMPTY:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Bạn phải điền đủ các thông tin");
                    break;
                case MysqlCarTravelDao.RESULT_ERROR_CMT:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Định dạng chứng minh thư không đúng.Vui lòng nhập lại");
                    break;
                case MysqlCarTravelDao.RESULT_NOT_EXIT_TICKET:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Thông tin nhập không chính xác.Vui lòng kiểm tra lại thông tin trong email");
                    break;
                case MysqlCarTravelDao.RESULT_SUCCESS:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Hủy vé thành công");
                    jTextField_maChuyenXe.setText("");
                    jTextField_cmtKhach.setText("");
                    break;
                case MysqlCarTravelDao.RESULT_EXCEPTION:
                    JOptionPane.showMessageDialog(jDialog_bookTicket, "Đã có lỗi xảy ra.Vui lòng thử lại sau");
                    break;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseClicked
        // TODO add your handling code here:
        stt++;
        setVisiablePrevious();
        setVisiableNext();
        int checkStt = 0;
        if ((float) listInformations.size() / 4 == listInformations.size() / 4) {
            checkStt = listInformations.size() / 4;
        } else {
            checkStt = listInformations.size() / 4 + 1;
        }
        if (stt <= checkStt) {
            jPanel4.removeAll();
            jPanel4.revalidate();
            jPanel4.repaint();
            ic.displayInformation(jPanel4, jPanel_news, listInformations, stt);
        }
    }//GEN-LAST:event_jLabel_nextMouseClicked

    private void jLabel_beforeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_beforeMouseClicked
        // TODO add your handling code here:
        stt--;
        setVisiablePrevious();
        setVisiableNext();
        if (stt >= 1) {
            jPanel4.removeAll();
            jPanel4.revalidate();
            jPanel4.repaint();
            ic.displayInformation(jPanel4, jPanel_news, listInformations, stt);
        }
    }//GEN-LAST:event_jLabel_beforeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        stt = 1;
        setVisiablePrevious();
        setVisiableNext();
        jPanel4.removeAll();
        jPanel4.revalidate();
        jPanel4.repaint();
        ic.displayInformation(jPanel4, jPanel_news, listInformations, stt);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void setVisiablePrevious() {
        if (stt == 1) {
            jLabel_before.setVisible(false);
        } else {
            jLabel_before.setVisible(true);
        }
    }

    private void setVisiableNext() {
        int checkStt = 0;
        if ((float) listInformations.size() / 4 == listInformations.size() / 4) {
            checkStt = listInformations.size() / 4;
        } else {
            checkStt = (int) (listInformations.size() / 4) + 1;
        }
        if (stt == checkStt) {
            jLabel_next.setVisible(false);
            System.out.println(stt + " " + checkStt);
            System.out.println((float) listInformations.size() / 4);
        } else {
            jLabel_next.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog_bookTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_before;
    private javax.swing.JLabel jLabel_next;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_bookticket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_bookticket;
    private javax.swing.JPanel jPanel_news;
    private javax.swing.JPanel jPanel_searchInfor;
    private javax.swing.JPanel jPanel_unbookticket;
    private javax.swing.JPopupMenu jPopupMenu_bookticket;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JRadioButton jRadioButton_nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_bsx;
    private javax.swing.JTextField jTextField_cmt;
    private javax.swing.JTextField jTextField_cmtKhach;
    private javax.swing.JTextField jTextField_diaChi;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_giaVe;
    private javax.swing.JTextField jTextField_lichTrinh;
    private javax.swing.JTextField jTextField_loTrinh;
    private javax.swing.JTextField jTextField_maChuyenXe;
    private javax.swing.JTextField jTextField_nhaXe;
    private javax.swing.JTextField jTextField_sdt;
    private javax.swing.JTextField jTextField_searchCarForBookTicket;
    private javax.swing.JTextField jTextField_soGhe;
    private javax.swing.JTextField jTextField_ten;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1_ngayDatVeDi;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker_ngaySinh;
    // End of variables declaration//GEN-END:variables

    private void setVisiableNews() {
        jPanel_news.setVisible(true);
        jPanel_bookticket.setVisible(false);
        jPanel_unbookticket.setVisible(false);
        jPanel_searchInfor.setVisible(false);
    }

    private void setVisiableBookTicket() {
        jPanel_news.setVisible(false);
        jPanel_bookticket.setVisible(true);
        jPanel_unbookticket.setVisible(false);
        jPanel_searchInfor.setVisible(false);
    }

    private void setVisiableUnBookTicket() {
        jPanel_news.setVisible(false);
        jPanel_bookticket.setVisible(false);
        jPanel_unbookticket.setVisible(true);
        jPanel_searchInfor.setVisible(false);
    }

    private void setVisiableSearchInfor() {
        jPanel_news.setVisible(false);
        jPanel_bookticket.setVisible(false);
        jPanel_unbookticket.setVisible(false);
        jPanel_searchInfor.setVisible(true);
    }
}
